// <auto-generated />
namespace Asp.netMVC_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class avb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(avb));
        
        string IMigrationMetadata.Id
        {
            get { return "202404041058147_avb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
